# Docker MySQL Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.placeholder-replacement=false

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#OAuth2.0 Client Registration details
oauth.client.id=scaler
oauth.client.secret=scaler-secret
oauth.client.redirectUri=https://oauth.pstmn.io/v1/callback
oauth.client.postLogoutRedirectUri = https://oauth.pstmn.io/v1/callback

logging.level.org.springframework.web = TRACE
logging.level.org.springframework.security = TRACE